# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /users/cao/cc3801875/Documents/Tau-h

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /users/cao/cc3801875/Documents/Tau-h

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /users/cao/cc3801875/Documents/Tau-h/CMakeFiles /users/cao/cc3801875/Documents/Tau-h/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /users/cao/cc3801875/Documents/Tau-h/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tah-common-obj

# Build rule for target.
tah-common-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tah-common-obj
.PHONY : tah-common-obj

# fast build rule for target.
tah-common-obj/fast:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/build
.PHONY : tah-common-obj/fast

#=============================================================================
# Target rules for targets named tah-detect-exe

# Build rule for target.
tah-detect-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tah-detect-exe
.PHONY : tah-detect-exe

# fast build rule for target.
tah-detect-exe/fast:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/build
.PHONY : tah-detect-exe/fast

#=============================================================================
# Target rules for targets named tah-visu-exe

# Build rule for target.
tah-visu-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tah-visu-exe
.PHONY : tah-visu-exe

# fast build rule for target.
tah-visu-exe/fast:
	$(MAKE) -f CMakeFiles/tah-visu-exe.dir/build.make CMakeFiles/tah-visu-exe.dir/build
.PHONY : tah-visu-exe/fast

#=============================================================================
# Target rules for targets named tah-check-exe

# Build rule for target.
tah-check-exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tah-check-exe
.PHONY : tah-check-exe

# fast build rule for target.
tah-check-exe/fast:
	$(MAKE) -f CMakeFiles/tah-check-exe.dir/build.make CMakeFiles/tah-check-exe.dir/build
.PHONY : tah-check-exe/fast

#=============================================================================
# Target rules for targets named ffmpeg-io-slib

# Build rule for target.
ffmpeg-io-slib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffmpeg-io-slib
.PHONY : ffmpeg-io-slib

# fast build rule for target.
ffmpeg-io-slib/fast:
	$(MAKE) -f lib/ffmpeg-io/CMakeFiles/ffmpeg-io-slib.dir/build.make lib/ffmpeg-io/CMakeFiles/ffmpeg-io-slib.dir/build
.PHONY : ffmpeg-io-slib/fast

#=============================================================================
# Target rules for targets named ffmpeg-io-obj

# Build rule for target.
ffmpeg-io-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ffmpeg-io-obj
.PHONY : ffmpeg-io-obj

# fast build rule for target.
ffmpeg-io-obj/fast:
	$(MAKE) -f lib/ffmpeg-io/CMakeFiles/ffmpeg-io-obj.dir/build.make lib/ffmpeg-io/CMakeFiles/ffmpeg-io-obj.dir/build
.PHONY : ffmpeg-io-obj/fast

#=============================================================================
# Target rules for targets named nrc-slib

# Build rule for target.
nrc-slib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrc-slib
.PHONY : nrc-slib

# fast build rule for target.
nrc-slib/fast:
	$(MAKE) -f lib/nrc2/CMakeFiles/nrc-slib.dir/build.make lib/nrc2/CMakeFiles/nrc-slib.dir/build
.PHONY : nrc-slib/fast

#=============================================================================
# Target rules for targets named nrc-obj

# Build rule for target.
nrc-obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nrc-obj
.PHONY : nrc-obj

# fast build rule for target.
nrc-obj/fast:
	$(MAKE) -f lib/nrc2/CMakeFiles/nrc-obj.dir/build.make lib/nrc2/CMakeFiles/nrc-obj.dir/build
.PHONY : nrc-obj/fast

src/check/Main_check.o: src/check/Main_check.c.o

.PHONY : src/check/Main_check.o

# target to build an object file
src/check/Main_check.c.o:
	$(MAKE) -f CMakeFiles/tah-check-exe.dir/build.make CMakeFiles/tah-check-exe.dir/src/check/Main_check.c.o
.PHONY : src/check/Main_check.c.o

src/check/Main_check.i: src/check/Main_check.c.i

.PHONY : src/check/Main_check.i

# target to preprocess a source file
src/check/Main_check.c.i:
	$(MAKE) -f CMakeFiles/tah-check-exe.dir/build.make CMakeFiles/tah-check-exe.dir/src/check/Main_check.c.i
.PHONY : src/check/Main_check.c.i

src/check/Main_check.s: src/check/Main_check.c.s

.PHONY : src/check/Main_check.s

# target to generate assembly for a file
src/check/Main_check.c.s:
	$(MAKE) -f CMakeFiles/tah-check-exe.dir/build.make CMakeFiles/tah-check-exe.dir/src/check/Main_check.c.s
.PHONY : src/check/Main_check.c.s

src/common/Args.o: src/common/Args.c.o

.PHONY : src/common/Args.o

# target to build an object file
src/common/Args.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Args.c.o
.PHONY : src/common/Args.c.o

src/common/Args.i: src/common/Args.c.i

.PHONY : src/common/Args.i

# target to preprocess a source file
src/common/Args.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Args.c.i
.PHONY : src/common/Args.c.i

src/common/Args.s: src/common/Args.c.s

.PHONY : src/common/Args.s

# target to generate assembly for a file
src/common/Args.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Args.c.s
.PHONY : src/common/Args.c.s

src/common/DebugUtil.o: src/common/DebugUtil.c.o

.PHONY : src/common/DebugUtil.o

# target to build an object file
src/common/DebugUtil.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/DebugUtil.c.o
.PHONY : src/common/DebugUtil.c.o

src/common/DebugUtil.i: src/common/DebugUtil.c.i

.PHONY : src/common/DebugUtil.i

# target to preprocess a source file
src/common/DebugUtil.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/DebugUtil.c.i
.PHONY : src/common/DebugUtil.c.i

src/common/DebugUtil.s: src/common/DebugUtil.c.s

.PHONY : src/common/DebugUtil.s

# target to generate assembly for a file
src/common/DebugUtil.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/DebugUtil.c.s
.PHONY : src/common/DebugUtil.c.s

src/common/Features.o: src/common/Features.c.o

.PHONY : src/common/Features.o

# target to build an object file
src/common/Features.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Features.c.o
.PHONY : src/common/Features.c.o

src/common/Features.i: src/common/Features.c.i

.PHONY : src/common/Features.i

# target to preprocess a source file
src/common/Features.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Features.c.i
.PHONY : src/common/Features.c.i

src/common/Features.s: src/common/Features.c.s

.PHONY : src/common/Features.s

# target to generate assembly for a file
src/common/Features.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Features.c.s
.PHONY : src/common/Features.c.s

src/common/Tracking.o: src/common/Tracking.c.o

.PHONY : src/common/Tracking.o

# target to build an object file
src/common/Tracking.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Tracking.c.o
.PHONY : src/common/Tracking.c.o

src/common/Tracking.i: src/common/Tracking.c.i

.PHONY : src/common/Tracking.i

# target to preprocess a source file
src/common/Tracking.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Tracking.c.i
.PHONY : src/common/Tracking.c.i

src/common/Tracking.s: src/common/Tracking.c.s

.PHONY : src/common/Tracking.s

# target to generate assembly for a file
src/common/Tracking.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Tracking.c.s
.PHONY : src/common/Tracking.c.s

src/common/Validation.o: src/common/Validation.c.o

.PHONY : src/common/Validation.o

# target to build an object file
src/common/Validation.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Validation.c.o
.PHONY : src/common/Validation.c.o

src/common/Validation.i: src/common/Validation.c.i

.PHONY : src/common/Validation.i

# target to preprocess a source file
src/common/Validation.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Validation.c.i
.PHONY : src/common/Validation.c.i

src/common/Validation.s: src/common/Validation.c.s

.PHONY : src/common/Validation.s

# target to generate assembly for a file
src/common/Validation.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Validation.c.s
.PHONY : src/common/Validation.c.s

src/common/Video.o: src/common/Video.c.o

.PHONY : src/common/Video.o

# target to build an object file
src/common/Video.c.o:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Video.c.o
.PHONY : src/common/Video.c.o

src/common/Video.i: src/common/Video.c.i

.PHONY : src/common/Video.i

# target to preprocess a source file
src/common/Video.c.i:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Video.c.i
.PHONY : src/common/Video.c.i

src/common/Video.s: src/common/Video.c.s

.PHONY : src/common/Video.s

# target to generate assembly for a file
src/common/Video.c.s:
	$(MAKE) -f CMakeFiles/tah-common-obj.dir/build.make CMakeFiles/tah-common-obj.dir/src/common/Video.c.s
.PHONY : src/common/Video.c.s

src/detect/Ballon.o: src/detect/Ballon.c.o

.PHONY : src/detect/Ballon.o

# target to build an object file
src/detect/Ballon.c.o:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Ballon.c.o
.PHONY : src/detect/Ballon.c.o

src/detect/Ballon.i: src/detect/Ballon.c.i

.PHONY : src/detect/Ballon.i

# target to preprocess a source file
src/detect/Ballon.c.i:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Ballon.c.i
.PHONY : src/detect/Ballon.c.i

src/detect/Ballon.s: src/detect/Ballon.c.s

.PHONY : src/detect/Ballon.s

# target to generate assembly for a file
src/detect/Ballon.c.s:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Ballon.c.s
.PHONY : src/detect/Ballon.c.s

src/detect/CCL_LSL.o: src/detect/CCL_LSL.c.o

.PHONY : src/detect/CCL_LSL.o

# target to build an object file
src/detect/CCL_LSL.c.o:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/CCL_LSL.c.o
.PHONY : src/detect/CCL_LSL.c.o

src/detect/CCL_LSL.i: src/detect/CCL_LSL.c.i

.PHONY : src/detect/CCL_LSL.i

# target to preprocess a source file
src/detect/CCL_LSL.c.i:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/CCL_LSL.c.i
.PHONY : src/detect/CCL_LSL.c.i

src/detect/CCL_LSL.s: src/detect/CCL_LSL.c.s

.PHONY : src/detect/CCL_LSL.s

# target to generate assembly for a file
src/detect/CCL_LSL.c.s:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/CCL_LSL.c.s
.PHONY : src/detect/CCL_LSL.c.s

src/detect/KPPV.o: src/detect/KPPV.c.o

.PHONY : src/detect/KPPV.o

# target to build an object file
src/detect/KPPV.c.o:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/KPPV.c.o
.PHONY : src/detect/KPPV.c.o

src/detect/KPPV.i: src/detect/KPPV.c.i

.PHONY : src/detect/KPPV.i

# target to preprocess a source file
src/detect/KPPV.c.i:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/KPPV.c.i
.PHONY : src/detect/KPPV.c.i

src/detect/KPPV.s: src/detect/KPPV.c.s

.PHONY : src/detect/KPPV.s

# target to generate assembly for a file
src/detect/KPPV.c.s:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/KPPV.c.s
.PHONY : src/detect/KPPV.c.s

src/detect/Main_detect.o: src/detect/Main_detect.c.o

.PHONY : src/detect/Main_detect.o

# target to build an object file
src/detect/Main_detect.c.o:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Main_detect.c.o
.PHONY : src/detect/Main_detect.c.o

src/detect/Main_detect.i: src/detect/Main_detect.c.i

.PHONY : src/detect/Main_detect.i

# target to preprocess a source file
src/detect/Main_detect.c.i:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Main_detect.c.i
.PHONY : src/detect/Main_detect.c.i

src/detect/Main_detect.s: src/detect/Main_detect.c.s

.PHONY : src/detect/Main_detect.s

# target to generate assembly for a file
src/detect/Main_detect.c.s:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Main_detect.c.s
.PHONY : src/detect/Main_detect.c.s

src/detect/Threshold.o: src/detect/Threshold.c.o

.PHONY : src/detect/Threshold.o

# target to build an object file
src/detect/Threshold.c.o:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Threshold.c.o
.PHONY : src/detect/Threshold.c.o

src/detect/Threshold.i: src/detect/Threshold.c.i

.PHONY : src/detect/Threshold.i

# target to preprocess a source file
src/detect/Threshold.c.i:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Threshold.c.i
.PHONY : src/detect/Threshold.c.i

src/detect/Threshold.s: src/detect/Threshold.c.s

.PHONY : src/detect/Threshold.s

# target to generate assembly for a file
src/detect/Threshold.c.s:
	$(MAKE) -f CMakeFiles/tah-detect-exe.dir/build.make CMakeFiles/tah-detect-exe.dir/src/detect/Threshold.c.s
.PHONY : src/detect/Threshold.c.s

src/visu/Main_visu.o: src/visu/Main_visu.c.o

.PHONY : src/visu/Main_visu.o

# target to build an object file
src/visu/Main_visu.c.o:
	$(MAKE) -f CMakeFiles/tah-visu-exe.dir/build.make CMakeFiles/tah-visu-exe.dir/src/visu/Main_visu.c.o
.PHONY : src/visu/Main_visu.c.o

src/visu/Main_visu.i: src/visu/Main_visu.c.i

.PHONY : src/visu/Main_visu.i

# target to preprocess a source file
src/visu/Main_visu.c.i:
	$(MAKE) -f CMakeFiles/tah-visu-exe.dir/build.make CMakeFiles/tah-visu-exe.dir/src/visu/Main_visu.c.i
.PHONY : src/visu/Main_visu.c.i

src/visu/Main_visu.s: src/visu/Main_visu.c.s

.PHONY : src/visu/Main_visu.s

# target to generate assembly for a file
src/visu/Main_visu.c.s:
	$(MAKE) -f CMakeFiles/tah-visu-exe.dir/build.make CMakeFiles/tah-visu-exe.dir/src/visu/Main_visu.c.s
.PHONY : src/visu/Main_visu.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tah-common-obj"
	@echo "... tah-detect-exe"
	@echo "... tah-visu-exe"
	@echo "... edit_cache"
	@echo "... tah-check-exe"
	@echo "... ffmpeg-io-slib"
	@echo "... ffmpeg-io-obj"
	@echo "... nrc-slib"
	@echo "... nrc-obj"
	@echo "... src/check/Main_check.o"
	@echo "... src/check/Main_check.i"
	@echo "... src/check/Main_check.s"
	@echo "... src/common/Args.o"
	@echo "... src/common/Args.i"
	@echo "... src/common/Args.s"
	@echo "... src/common/DebugUtil.o"
	@echo "... src/common/DebugUtil.i"
	@echo "... src/common/DebugUtil.s"
	@echo "... src/common/Features.o"
	@echo "... src/common/Features.i"
	@echo "... src/common/Features.s"
	@echo "... src/common/Tracking.o"
	@echo "... src/common/Tracking.i"
	@echo "... src/common/Tracking.s"
	@echo "... src/common/Validation.o"
	@echo "... src/common/Validation.i"
	@echo "... src/common/Validation.s"
	@echo "... src/common/Video.o"
	@echo "... src/common/Video.i"
	@echo "... src/common/Video.s"
	@echo "... src/detect/Ballon.o"
	@echo "... src/detect/Ballon.i"
	@echo "... src/detect/Ballon.s"
	@echo "... src/detect/CCL_LSL.o"
	@echo "... src/detect/CCL_LSL.i"
	@echo "... src/detect/CCL_LSL.s"
	@echo "... src/detect/KPPV.o"
	@echo "... src/detect/KPPV.i"
	@echo "... src/detect/KPPV.s"
	@echo "... src/detect/Main_detect.o"
	@echo "... src/detect/Main_detect.i"
	@echo "... src/detect/Main_detect.s"
	@echo "... src/detect/Threshold.o"
	@echo "... src/detect/Threshold.i"
	@echo "... src/detect/Threshold.s"
	@echo "... src/visu/Main_visu.o"
	@echo "... src/visu/Main_visu.i"
	@echo "... src/visu/Main_visu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

